### ISSUE TITLE
Still getting blanks in translate.py output

### ISSUE THREAD

**Issue by devinbostIL** [Ubiqus/OpenNMT-py#11]
This is a carry-over from: https://github.com/OpenNMT/OpenNMT-py/issues/743

When I run translate.py on a model that was trained to completion via the steps here: https://github.com/Ubiqus/OpenNMT-py/issues/4

I'm getting blanks in the output even for small input files, but only some of the predictions are blank. I also tried running: 

`python translate.py -model C:\src\pyopennmt\ubiqus\OpenNMT-py\tc-offense-classifier-character_v5_step_1000000.pt -src C:\src\torchevere-offensive-classifier\test2.txt -v`

so that I could see each prediction in the console, and many of the prediction values are still blank. Any idea what could be causing this?

**Comment by vince62s** [comment]
are you working on a translation task or something else ?
I am mostly working on the transformer model, but I was also able to train and translate with a LSTM one.

**Comment by vince62s** [comment]
are you saying the target is always 1 or 0 for an input=a sentence ?
and you mean you have empty output at times ?
did it ever work 100% with an output being never empty (with openNMT-py or another toolkit) ?

**Comment by devinbostIL** [comment]
> are you saying the target is always 1 or 0 for an input=a sentence ?
That is correct.

> and you mean you have empty output at times ?
That's also correct.

> did it ever work 100% with an output being never empty (with openNMT-py or another toolkit) ?
I also had this problem when running this particular data model through openNMT-py version 0.3.1.post2. 
When run with a different data model (when actually translating a sentence to another sentence), I did not have this issue when running a previous version of openNMT-py, but I'm not sure which version we were using in that case (most likely version 0.3.1.post2 or older). 
I have not evaluated the latest version of openNMT-py on a sentence-to-sentence model to determine if it also results in blank lines in the output of running `translate.py`.

**Comment by vince62s** [comment]
you could try 2 things:

1- beam_size 1: greedy search may help in your case
2- translate with -min_length 1

**Comment by vince62s** [comment]
closing this, reopen if needed.
